server:
  port: 8082

management:
  security:
    enabled: false

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka}:8761/eureka/

logging:
  level:
    ROOT: INFO
    org.hibernate.tool.hbm2ddl: DEBUG
    org.hibernate.SQL: DEBUG

---

spring:
  profiles: docker

---

spring:
  profiles: postgres
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:datastore}:5432/product
    username: dbuser
    password: dbpass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none