server:
  port: 8082

management:
  security:
    enabled: false

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5

logging:
  level:
    ROOT: INFO
    org.hibernate.tool.hbm2ddl: DEBUG
    org.hibernate.SQL: DEBUG